<?php

namespace App\Models;

use App\Enums\ThreadStatus;
use Database\Factories\ThreadFactory;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Thread extends Model
{
    /** @use HasFactory<ThreadFactory> */
    use HasFactory, HasUuids;

    protected $fillable = [
        'project_id',
        'template_type',
        'objective',
        'theme_context',
        'status',
        'protocol',
        'state_data',
        'export_yaml',
        'agent_interactions',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'status' => ThreadStatus::class,
            'template_type' => \App\Enums\TemplateType::class,
            'protocol' => 'array',
            'state_data' => 'array',
            'agent_interactions' => 'array',
        ];
    }

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['questions', 'answers'];

    /**
     * Get the clarifying questions generated by the AI.
     */
    protected function questions(): Attribute
    {
        return Attribute::make(
            get: fn () => $this->agent_interactions['intent_clarifier_questions']['output']['questions'] ?? null,
        );
    }

    /**
     * Get the user's answers.
     */
    protected function answers(): Attribute
    {
        return Attribute::make(
            get: fn () => $this->state_data['answers'] ?? null,
        );
    }

    /**
     * Record an interaction with an agent.
     */
    public function recordAgentInteraction(string $agentName, ?string $conversationId, mixed $input, mixed $output): void
    {
        $interactions = $this->agent_interactions ?? [];

        $interactions[$agentName] = [
            'conversation_id' => $conversationId,
            'input' => $input,
            'output' => $output,
            'updated_at' => now()->toIso8601String(),
        ];

        $this->update(['agent_interactions' => $interactions]);
    }

    /**
     * Get the conversation ID for a specific agent.
     */
    public function getConversationId(string $agentName): ?string
    {
        return $this->agent_interactions[$agentName]['conversation_id'] ?? null;
    }

    /**
     * Get the project that owns the thread.
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }
}
